version: '3.8'

services:
  floci:
    image: floci/floci:latest
    container_name: devops-floci
    ports:
      - "4566:4566"
    networks:
      - devops-network

  redis:
    image: redis:7-alpine
    container_name: devops-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - devops-network

  config-service:
    build:
      context: .
      dockerfile: ./config-service/Dockerfile
    container_name: devops-config-service
    ports:
      - "8082:8082"
    depends_on:
      - floci
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://floci:4566/devops_config
    networks:
      - devops-network

  gateway-service:
    build:
      context: .
      dockerfile: ./gateway-service/Dockerfile
    container_name: devops-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - floci
      - config-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://floci:4566/devops_users
      CONFIG_SERVICE_URL: http://config-service:8082
      COLLECTOR_SERVICE_URL: http://log-collector-service:8083
      ANALYZER_SERVICE_URL: http://log-analyzer-service:8081
      SCANNER_SERVICE_URL: http://repo-scanner-service:8085
      INCIDENT_SERVICE_URL: http://incident-service:8084
      NOTIFICATION_SERVICE_URL: http://notification-service:8086
    networks:
      - devops-network

  incident-service:
    build:
      context: .
      dockerfile: ./incident-service/Dockerfile
    container_name: devops-incident-service
    ports:
      - "8084:8084"
    depends_on:
      - floci
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: floci:4566
      SPRING_DATA_MONGODB_URI: mongodb://floci:4566/devops_incidents
    networks:
      - devops-network

  repo-scanner-service:
    build:
      context: .
      dockerfile: ./repo-scanner-service/Dockerfile
    container_name: devops-repo-scanner-service
    ports:
      - "8085:8085"
    depends_on:
      - floci
      - redis
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: floci:4566
      SPRING_DATA_REDIS_HOST: redis
      SERVICES_CONFIG_URL: http://config-service:8082/api/v1/config
      SERVICES_INCIDENT_URL: http://incident-service:8084/api/v1/incidents
    networks:
      - devops-network

  log-analyzer-service:
    build:
      context: .
      dockerfile: ./log-analyzer-service/Dockerfile
    container_name: devops-log-analyzer-service
    ports:
      - "8086:8086"
    depends_on:
      - floci
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: floci:4566
      SERVICES_CONFIG_URL: http://config-service:8082/api/v1/config
      SERVICES_INCIDENT_URL: http://incident-service:8084/api/v1/incidents
    networks:
      - devops-network

  log-collector-service:
    build:
      context: .
      dockerfile: ./log-collector-service/Dockerfile
    container_name: devops-log-collector-service
    ports:
      - "8087:8083"
    depends_on:
      - floci
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: floci:4566
      SERVICES_CONFIG_URL: http://config-service:8082/api/v1/config
      SERVICES_ANALYZER_URL: http://log-analyzer-service:8081/api/v1/analyzer/logs
      SPLUNK_MOCK_URL: http://localhost:8083/api/v1/mock/splunk/logs
    networks:
      - devops-network

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: devops-notification-service
    ports:
      - "8088:8088"
    depends_on:
      - floci
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://floci:4566/devops_notifications
    networks:
      - devops-network

  dashboard-ui:
    build:
      context: ./dashboard-ui
    container_name: devops-dashboard-ui
    ports:
      - "5173:80"
    depends_on:
      - gateway-service
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge



